"""
Creative Director Agent — Rule Set, Director Brief, Legacy Sequence Fallback.

Generates the Style Brief interpretation used by run_creative_direction():
  generate_rule_set()          -> Boolean/keyword constraints (HARD_FILTER_PEOPLE, etc.)
  generate_director_brief()    -> thematic_niche / color_profile_target for the Judge's Verdict
  select_sequence_from_batch() -> legacy fallback-of-a-fallback sequence selector

The Judge's Verdict itself is generated by src/jury_engine.py's multi-
persona jury, not this module — creative_director.py imports
generate_judges_verdict_8b from jury_engine directly.

Rule-set/brief generation is keyword-first — the same keyword tables already
used elsewhere in creative_director.py (_compute_brief_scores, _empty_brief_
detected) — with an optional GGUF (models/deepseek-r1-8b-q5.gguf) refinement
pass only when the keyword pass finds nothing at all. Every public function
here degrades gracefully and never raises — the pipeline must complete even
with no GGUF present and Ollama unreachable.

GPU offload: _load_agent_llm() probes an offload ladder (full -> partial ->
CPU) rather than the old hardcoded n_gpu_layers=0. This step runs at Step 1,
before any other GPU model in the pipeline has loaded, so there's nothing to
compete with — CPU-only here was inherited caution, not a real constraint.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

_ROOT = Path(__file__).resolve().parent.parent

# Grammar-constrained decoding for the rule-set refinement call — same
# pattern as vlm_niche_detector.py's _GRAMMAR_SRC (grammar built once,
# passed per-call via grammar=).
_RULE_SET_GRAMMAR_SRC = r'''
root   ::= "{" ws '"HARD_FILTER_PEOPLE"' ws ":" ws bool ws "," ws '"GEOMETRIC_PRIORITY"' ws ":" ws geo ws "," ws '"LIGHTING_MOOD"' ws ":" ws string ws "}"
bool   ::= "true" | "false"
geo    ::= "\"High\"" | "\"Normal\""
string ::= "\"" ([^"\\] | "\\" .)* "\""
ws     ::= [ \t\r\n]*
'''
_rule_set_grammar: object = None


def _load_rule_set_grammar():
    global _rule_set_grammar
    if _rule_set_grammar is not None:
        return _rule_set_grammar
    try:
        from llama_cpp import LlamaGrammar
        _rule_set_grammar = LlamaGrammar.from_string(_RULE_SET_GRAMMAR_SRC)
    except Exception as e:
        print(f"[cda] rule-set grammar build failed ({e}) — falling back to unconstrained decoding")
        _rule_set_grammar = None
    return _rule_set_grammar

# ── Keyword tables (mirror creative_director.py's existing heuristics) ───────

_EMPTY_KW = {"empty", "liminal", "desert", "void", "abandoned", "desolate"}
_GEO_KW   = {"geometry", "geometric", "architecture", "architectural", "pattern",
             "lines", "symmetry", "abstract", "structure", "grid", "form",
             "minimal", "minimalist"}
_MOOD_KW: list[tuple[str, set[str]]] = [
    ("moody/high-contrast", {"rain", "wet", "reflection", "reflections", "puddle",
                              "fog", "mist", "shadow", "shadows", "night", "dusk",
                              "overcast", "cloudy", "moody", "hazy"}),
    ("warm/golden",         {"golden", "sunset", "sunrise", "dawn", "warm"}),
    ("neon/night",          {"neon", "twilight", "blue hour"}),
]
_COMPETITION_KW = {
    "competition", "award", "submit", "submission", "contest", "prize",
    "jury", "festival", "portfolio review", "standalone", "single image",
}
_NICHE_KW: dict[str, set[str]] = {
    "portrait":     {"portrait", "faces", "human", "stranger", "strangers"},
    "architecture": {"architecture", "architectural", "geometry", "geometric", "structure"},
    "documentary":  {"documentary", "candid", "life", "community", "culture"},
    "night street": {"night", "neon", "dusk", "twilight"},
    "minimalist":   {"minimal", "minimalist", "negative space", "empty", "void"},
}
_COLOR_KW: dict[str, set[str]] = {
    "black and white": {"black and white", "b&w", "monochrome", "grayscale"},
    "warm/golden":     {"warm", "golden", "sunset", "sunrise"},
    "cool/blue":       {"cool", "blue", "night", "rain", "wet"},
    "neon/saturated":  {"neon", "vibrant", "saturated"},
}


@dataclass
class DirectorBrief:
    thematic_niche: str
    color_profile_target: str


# ── Shared CPU GGUF singleton (loaded lazily, reused across Step 1's two
#    calls within one run_creative_direction() invocation, then explicitly
#    unloaded — an 8B Q5 GGUF is ~5-6GB of CPU RAM and this pipeline runs
#    once per user action, not per-frame, so it should not stay resident
#    between requests the way critique_engine's GPU model does) ─────────────

def unload_agent_model() -> None:
    """No-op, deliberately.

    This used to free a SECOND Llama instance of the same weights this module
    now shares with local_llm. It is called mid-pipeline, immediately before
    ask_local_art_director needs those very weights -- so evicting them here
    forced a multi-GB reload seconds later. Kept as a no-op because
    creative_director calls it and the call site is not worth churning.
    """
    return None

def _extract_json_obj(raw: str) -> Optional[dict]:
    """Brace-balanced JSON object extraction, tolerant of <think> preambles
    and surrounding prose — same defensive style as critique_engine's
    bracket-matching JSON extraction."""
    raw = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
    start = raw.find("{")
    if start < 0:
        return None
    depth = 0
    in_str = False
    esc = False
    for i, ch in enumerate(raw[start:], start):
        if esc:
            esc = False
            continue
        if ch == "\\" and in_str:
            esc = True
            continue
        if ch == '"':
            in_str = not in_str
            continue
        if in_str:
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                try:
                    obj = json.loads(raw[start:i + 1])
                    return obj if isinstance(obj, dict) else None
                except Exception:
                    return None
    return None


# ── generate_rule_set ─────────────────────────────────────────────────────

def _keyword_rule_set(style_prompt: str) -> dict:
    text = (style_prompt or "").lower()
    matched_kw = [kw for kw in (_EMPTY_KW | _GEO_KW) if kw in text]
    return {
        "HARD_FILTER_PEOPLE": any(kw in text for kw in _EMPTY_KW),
        "GEOMETRIC_PRIORITY": "High" if any(kw in text for kw in _GEO_KW) else "Normal",
        "LIGHTING_MOOD": next((label for label, kws in _MOOD_KW if any(kw in text for kw in kws)), "neutral"),
        "BRIEF_KEYWORDS": matched_kw,
    }


# Circuit breaker: some llama-cpp-python + GGUF combinations hit a native
# access-violation inside the grammar-constrained sampler (observed with
# deepseek-r1-8b-q5.gguf on this build). It's caught as a Python exception,
# not a hard crash, but repeatedly retrying a known-broken path per call is
# wasteful — after the first grammar failure, fall back to unconstrained
# decoding (+ the existing brace-matching JSON extraction, which worked
# reliably before grammar was added) for the rest of the process.
_grammar_broken = False


def _gguf_refine_rule_set(style_prompt: str,
                          rag_phrases: "Optional[list[str]]" = None) -> "Optional[dict]":
    """Refine the keyword rule set with the shared text model, or None.

    Uses local_llm so there is ONE model per process. The previous version
    built its own Llama from a hardcoded path and applied a GBNF grammar.
    Grammar went away with the shared loader, and that is an improvement:
    measured on this task it scored 11/14 against 14/14 unconstrained,
    biasing toward small ids. It degrades the choice, not just the format.

    rag_phrases: reference-book concepts matched to this brief (Story/
    Competition RAG). They are appended to the prompt as context ONLY —
    the keyword path never sees them, so book vocabulary cannot
    accidentally trip the hardcoded keyword matchers.
    """
    import local_llm
    nl = chr(10)
    prompt = (
        "Analyze this street-photography style brief and answer with "
        "compact JSON only, no explanation:" + nl
        + 'Brief: "' + style_prompt[:200] + '"' + nl
    )
    if rag_phrases:
        prompt += ("Reference-book concepts the brief should honor: "
                   + "; ".join(p[:80] for p in rag_phrases[:6]) + nl)
    prompt += (
        '{"HARD_FILTER_PEOPLE": true|false, '
        '"GEOMETRIC_PRIORITY": "High"|"Normal", '
        '"LIGHTING_MOOD": "<=3 words"}' + nl
        + "JSON:"
    )
    raw = local_llm.generate(
        prompt,
        system="You answer with compact JSON and nothing else.",
        max_tokens=120,
        temperature=0.1,
    )
    if not raw:
        return None
    try:
        return _parse_rule_set_output(raw)
    except Exception as _e:
        print("[cda] rule-set refinement skipped: %s" % _e)
        return None


def _parse_rule_set_output(raw: str) -> Optional[dict]:
    obj = _extract_json_obj(raw)
    if not obj:
        return None
    return {
        "HARD_FILTER_PEOPLE": bool(obj.get("HARD_FILTER_PEOPLE", False)),
        "GEOMETRIC_PRIORITY": obj.get("GEOMETRIC_PRIORITY", "Normal") if obj.get("GEOMETRIC_PRIORITY") in ("High", "Normal") else "Normal",
        "LIGHTING_MOOD": str(obj.get("LIGHTING_MOOD", "neutral"))[:40],
    }


def generate_rule_set(style_prompt: str,
                      rag_phrases: "Optional[list[str]]" = None) -> dict:
    """
    Returns a fully-populated dict:
      {HARD_FILTER_PEOPLE: bool, GEOMETRIC_PRIORITY: "High"|"Normal",
       LIGHTING_MOOD: str, BRIEF_KEYWORDS: list[str]}

    Keyword heuristics are the primary path — the same signals that already
    drive _compute_brief_scores/_empty_brief_detected downstream, so the rule
    set stays consistent with how the brief is interpreted elsewhere in the
    pipeline. A CPU GGUF refinement pass only fires when the keyword pass
    finds nothing at all (a fully ambiguous brief) and never blocks or
    overrides a confident keyword match.

    rag_phrases: optional reference-book concepts (Story/Competition RAG).
    They enrich the GGUF refinement prompt only — see _gguf_refine_rule_set.
    """
    rule_set = _keyword_rule_set(style_prompt)
    if not rule_set["BRIEF_KEYWORDS"] and style_prompt.strip():
        refined = _gguf_refine_rule_set(style_prompt, rag_phrases=rag_phrases)
        if refined:
            rule_set.update(refined)
    return rule_set


# ── generate_director_brief ───────────────────────────────────────────────

def _keyword_director_brief(style_prompt: str) -> DirectorBrief:
    text = (style_prompt or "").lower()
    niche = next((name for name, kws in _NICHE_KW.items() if any(kw in text for kw in kws)), "street")
    color = next((name for name, kws in _COLOR_KW.items() if any(kw in text for kw in kws)), "natural")
    return DirectorBrief(thematic_niche=niche, color_profile_target=color)


def generate_director_brief(style_prompt: str) -> DirectorBrief:
    """
    Returns DirectorBrief(thematic_niche, color_profile_target).
    Keyword-first, same rationale as generate_rule_set. The call site
    (creative_director.py Step 1) already wraps this in try/except, but the
    function degrades gracefully on its own too, so it never needs that
    safety net to behave correctly.
    """
    return _keyword_director_brief(style_prompt)


# ── classify_mode (MoE auto-mode routing) ─────────────────────────────────

def classify_mode(style_prompt: str) -> str:
    """
    Classifies a style brief as "story" or "competition" for the frontend's
    seqMode="auto" option (frontend/src/App.tsx declares 'auto'|'director'|
    'story'|'competition' but only ever sends 'story'/'competition' today —
    this is what lets 'auto' resolve to a real mode). Keyword-first, same
    rationale as generate_rule_set/generate_director_brief: competition
    intent is a fairly explicit signal in the brief text ("award", "jury",
    "submission", ...), so a GGUF call isn't justified for this decision.
    Defaults to "story" — the more common case — when no signal is found.
    """
    text = (style_prompt or "").lower()
    if any(kw in text for kw in _COMPETITION_KW):
        return "competition"
    return "story"


# ── select_sequence_from_batch (legacy fallback-of-a-fallback) ───────────

def select_sequence_from_batch(
    candidates: list[dict],
    n_target: int,
    style_prompt: str,
    rule_set: dict,
) -> list[int]:
    """
    Only reached when ask_local_art_director() returns [] — which itself
    already falls back internally to top-N-by-score whenever candidate_pool
    is non-empty, so this path is close to unreachable in practice. Simple
    score-sort suffices: the candidate dict shape here (creative_director.py
    ~L1355-1369) carries per-aspect floats but no embeddings, so a
    diversity-aware pick isn't even possible from this data — no new GGUF
    call is justified for a fallback-of-a-fallback.

    candidates: each dict has at least "id" (int) and "score" (float).
    Returns list[int] of `id` values, length <= n_target.
    """
    if not candidates:
        return []
    ranked = sorted(candidates, key=lambda c: -float(c.get("score", 0.0)))
    return [c["id"] for c in ranked[:n_target]]
